"""SPARTA .in file generator — works with SPARTACase, no Qt dependency.

Two output modes, selected automatically:

* Surface-mesh mode (``grid.surface_file`` set): reads a .surf/STL mesh and
  applies wall models via ``surf_collide`` / ``surf_modify``.  Numbered computes.

* Boundary-wall mode (``wall.wall_boundary`` set, no surface mesh): the wall is a
  box face handled by ``bound_modify``.  This is the standard 1D axisymmetric
  stagnation-line (blunt-body) approximation.  Uses physically-named computes
  (gridprops, Tt, Tr, Tv, nrho_sp, kn), a ``thermal/grid`` temperature, a
  ``lambda/grid`` Knudsen field, and an AMR steady-state run loop.

CTFL group SPARTA extensions (see AdditionalCommands.readme) are emitted on the
``collide`` / ``collide_modify`` lines: ``relax variable vibmodel <MODEL>``,
``usecelltemperature``, ``parkeroff``, ``exchangestyle``, ``mgdscollide``.
"""

from __future__ import annotations

import os
from .engine import DerivedQuantities

_UNIT_SCALES = {"m": 1.0, "mm": 1e-3, "cm": 1e-2, "in": 0.0254}


def _s(v: float, digits: int = 8) -> str:
    return f"{v:.{digits}e}"


def _g(v: float) -> str:
    if v == 0.0:
        return "0"
    if abs(v) >= 1e4 or abs(v) < 1e-3:
        return f"{v:.6e}"
    return f"{v:.8g}"


def generate(case, derived: DerivedQuantities, dt_override: float = 0.0) -> str:
    """Return a complete SPARTA input script string for *case*.

    Parameters
    ----------
    case : SPARTACase
        The fully-specified case object.
    derived : DerivedQuantities
        Pre-computed quantities (from case.derived or engine.compute()).
    dt_override : float
        If > 0, use this timestep instead of the auto-recommended value.
    """
    lines: list[str] = []

    def L(text: str = ""):
        lines.append(text)

    geo  = case.grid
    fs   = case.freestream
    ph   = case.physics
    wall = case.wall
    sim  = case.sim
    cd   = case.compute_dump
    amr  = getattr(case, "amr", None)

    dt = dt_override if dt_override > 0 else derived.dt_recommended
    if dt <= 0:
        dt = 1e-8

    fnum = derived.fnum if derived.fnum > 0 else 1e10
    n_free = derived.n_free if derived.n_free > 0 else 1e20

    # freq=Nevery, samples=Nrepeat, window=Nfreq (coupled: window == freq*samples)
    nevery  = sim.freq
    nrepeat = sim.samples
    nfreq   = sim.window if sim.window > 0 else sim.freq * sim.samples
    warmup  = derived.warmup_steps if derived.warmup_steps > 0 else 10000

    # Inflow-declared species = every key in species_dict, in insertion order.
    # Zero-fraction entries (e.g. NO/N/O that only appear after reactions) are
    # kept so they are declared in the mixture; fractions are normalised over
    # the non-zero entries only.
    sp_ids = list(case.species_dict.keys())
    total_frac = sum(f for f in case.species_dict.values() if f > 0)

    # Full species set = inflow species + reaction-product species.
    # Reaction products must be declared explicitly via case.extra_species so
    # that the species list exactly matches the user-supplied chemistry file.
    # (Order is preserved; duplicates of inflow species are dropped.)
    explicit_extra = list(getattr(case, "extra_species", []) or [])
    _extra = [sp for sp in explicit_extra if sp not in sp_ids]
    all_sp_ids = sp_ids + _extra

    has_surf = bool(geo.surface_file)
    # Boundary-wall mode: no surface mesh, wall applied to a box face
    boundary_wall = (not has_surf) and bool(wall.wall_boundary)
    inflow_mix = sim.inflow_mixture if boundary_wall else "all"

    # ── Header ───────────────────────────────────────────────────────────────
    L(f"# SPARTA input script — {case.name}")
    L("# Generated by ctfl-sparta-tools")
    L()
    L("seed           12345")
    L(f"dimension      {geo.dimension}")
    L("units          si")

    bx, by, bz = geo.boundary_x, geo.boundary_y, geo.boundary_z
    if geo.symmetry == "axisymmetric" and geo.dimension == 2:
        by = "a" + (by[1] if len(by) > 1 else "o")
    L(f"boundary       {bx} {by} {bz}")
    L()

    # ── Box ──────────────────────────────────────────────────────────────────
    L("# --- Simulation box ---")
    L(f"create_box     {_g(geo.xlo)} {_g(geo.xhi)} {_g(geo.ylo)} {_g(geo.yhi)} {_g(geo.zlo)} {_g(geo.zhi)}")
    L(f"create_grid    {geo.n_cells_x} {geo.n_cells_y} {geo.n_cells_z}")
    L(f"balance_grid   rcb {geo.balance_mode}")
    L()

    # ── Global ────────────────────────────────────────────────────────────────
    L("# --- Global parameters ---")
    L(f"global         nrho {_s(n_free)} fnum {_s(fnum)}")
    L(f"global         vstream {_g(fs.velocity)} 0 0 temp {_g(fs.temperature)}")
    L()

    # ── Timestep ──────────────────────────────────────────────────────────────
    L("# --- Timestep ---")
    L(f"timestep       {_s(dt)}")
    L()

    # ── Species & mixture ─────────────────────────────────────────────────────
    L("# --- Species and mixture ---")
    if all_sp_ids:
        L(f"species        species.list {' '.join(all_sp_ids)}")
        L()
        if boundary_wall:
            # 1D stagnation-line convention: a single 'air' mixture with an
            # explicit emit/face inflow, then per-species fractions.
            L(f"mixture        {inflow_mix} {' '.join(sp_ids)} "
              f"nrho {_s(n_free)} vstream {_g(fs.velocity)} 0 0 temp {_g(fs.temperature)}")
            L()
            if sim.inflow_enabled:
                L(f"fix in1 emit/face {inflow_mix} {sim.inflow_face}")
                L(f"create_particles {inflow_mix} n 0")
                L()
            # Explicit fractions for every species (products get 0)
            for sp in all_sp_ids:
                frac = case.species_dict.get(sp, 0.0) / total_frac if total_frac > 0 else 0.0
                L(f"mixture        {inflow_mix} {sp} frac {_g(frac)}")
        else:
            L(f"mixture        all {' '.join(all_sp_ids)}")
            L(f"mixture        all nrho {_s(n_free)} vstream {_g(fs.velocity)} 0 0 temp {_g(fs.temperature)}")
            L()
            for sp in all_sp_ids:
                frac = case.species_dict.get(sp, 0.0) / total_frac if total_frac > 0 else 0.0
                L(f"mixture        all {sp} frac {_g(frac)}")
    L()

    # ── Surface mesh (only in surface-mesh mode) ──────────────────────────────
    if has_surf:
        surf_base = os.path.basename(geo.surface_file)
        unit_scale = _UNIT_SCALES.get(geo.surface_units, 1.0) * geo.surface_scale
        L("# --- Surface ---")
        if abs(unit_scale - 1.0) > 1e-10:
            L(f"read_surf      {surf_base} scale {_g(unit_scale)} {_g(unit_scale)} {_g(unit_scale)}")
        else:
            L(f"read_surf      {surf_base}")
        L(f"surf_collide   1 diffuse {_g(wall.temperature)} {_g(wall.accommodation)}")
        L("surf_modify    all collide 1")
        L()

    # ── Collision model ───────────────────────────────────────────────────────
    # CTFL: vibration model rides on the collide line via `relax variable vibmodel`.
    if ph.collision_model != "none" and sp_ids:
        L("# --- Collision model ---")
        collide_parts = ["collide vss all collision.list"]
        if ph.rot_relax_model == "parker" or ph.vib_relax_model:
            collide_parts.append("relax variable")
            if ph.vib_relax_model:
                collide_parts.append(f"vibmodel {ph.vib_relax_model}")
        if ph.use_cell_temperature:
            collide_parts.append("usecelltemperature yes")
        if ph.parker_off:
            collide_parts.append("parkeroff yes")
        L(" ".join(collide_parts))

        # collide_modify: rotate/vibrate smoothing + CTFL exchange/MGDS options
        cm_parts = ["collide_modify"]
        cm_parts.append(f"rotate {ph.rotate}")
        cm_parts.append(f"vibrate {ph.vibrate}")
        if ph.exchange_style:
            cm_parts.append(f"exchangestyle {ph.exchange_style}")
        cm_parts.append(f"mgdscollide {'yes' if ph.mgds_collide else 'no'}")
        L(" ".join(cm_parts))
        L()

    # ── Vibrational init (discrete only) ──────────────────────────────────────
    if ph.vibrate == "discrete" and sp_ids:
        t_vib_init = fs.t_vib if fs.t_vib > 0 else fs.temperature
        L("# --- Discrete vibrational energy ---")
        for sp in sp_ids:
            L(f"mixture        {inflow_mix} {sp} tvib {_g(t_vib_init)}")
        L()

    # ── Gas-phase chemistry ───────────────────────────────────────────────────
    if ph.react_enabled:
        react_file = os.path.basename(ph.react_file) if ph.react_file else "air.chem"
        L("# --- Chemistry ---")
        L(f"react         {ph.react_style} {react_file}")
        if ph.react_modify_partial_energy is not None:
            pe = "yes" if ph.react_modify_partial_energy else "no"
            L(f"react_modify  partial_energy {pe}")
        L()

    # ── Wall boundary conditions ──────────────────────────────────────────────
    if boundary_wall:
        L("# --- Wall boundary conditions ---")
        if wall.surf_react_enabled and wall.surf_react_file:
            L(f"surf_react     {wall.surf_react_id} {wall.surf_react_style} "
              f"{os.path.basename(wall.surf_react_file)}")
        L(f"surf_collide   {wall.surf_collide_id} diffuse "
          f"{_g(wall.temperature)} {_g(wall.accommodation)}")
        L(f"bound_modify   {wall.wall_boundary} collide {wall.surf_collide_id}")
        if wall.surf_react_enabled and wall.surf_react_file:
            L(f"bound_modify   {wall.wall_boundary} react {wall.surf_react_id}")
        L()

    # ── Computes / fixes / stats / dump ───────────────────────────────────────
    if boundary_wall and cd.named_ids:
        _emit_named_computes(L, case, nevery, nrepeat, nfreq)
    else:
        _emit_numbered_computes(L, case, has_surf, nevery, nrepeat, nfreq)

    # ── Run ───────────────────────────────────────────────────────────────────
    if boundary_wall and amr is not None and amr.enabled:
        _emit_amr_run(L, case, warmup)
    else:
        _emit_simple_run(L, case, has_surf, warmup, nevery, nrepeat, nfreq)

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
#  Named computes (boundary-wall / stagnation-line mode)
# ══════════════════════════════════════════════════════════════════════════════

def _emit_named_computes(L, case, nevery, nrepeat, nfreq):
    cd = case.compute_dump
    ph = case.physics

    L("# --- Averaging window variables ---")
    L(f"variable       window  equal {nfreq}")
    L(f"variable       samples equal {nrepeat}")
    L(f"variable       freq    equal {nevery}")
    L()

    L("# --- Computes ---")
    L("compute        gridprops grid all all n nrho u v")
    if cd.thermal_temp:
        L("compute        Tt        thermal/grid all all temp")
    if cd.grid_trot and ph.rotate != "no":
        L("compute        Tr        grid all all trot")
    if cd.grid_tvib and ph.vibrate != "no":
        L("compute        Tv        grid all all tvib")
    if cd.per_species_nrho:
        L("compute        nrho_sp   grid all species nrho")
    if cd.knudsen and cd.per_species_nrho and cd.thermal_temp:
        L("compute        kn        lambda/grid c_nrho_sp[*] c_Tt[1] lambda knall")
    L()

    L("# --- Time-averaging fixes ---")
    L("fix            gridprops ave/grid all ${freq} ${samples} ${window} c_gridprops[*]")
    if cd.thermal_temp:
        L("fix            Tt        ave/grid all ${freq} ${samples} ${window} c_Tt[*]")
    if cd.grid_trot and ph.rotate != "no":
        L("fix            Tr        ave/grid all ${freq} ${samples} ${window} c_Tr[*]")
    if cd.grid_tvib and ph.vibrate != "no":
        L("fix            Tv        ave/grid all ${freq} ${samples} ${window} c_Tv[*]")
    if cd.per_species_nrho:
        L("fix            nrho_sp   ave/grid all ${freq} ${samples} ${window} c_nrho_sp[*] ave one")
    if cd.knudsen and cd.per_species_nrho and cd.thermal_temp:
        L("fix            kn        ave/grid all ${freq} ${samples} ${window} c_kn[2] ave one")
    L()

    L("# --- Statistics ---")
    L(f"stats          {max(cd.stats_nevery, 1)}")
    L(f"stats_style    {cd.stats_fields}")
    L()

    # Build the dump field list from whichever fixes we emitted
    dump_fields = ["f_gridprops[*]"]
    if cd.thermal_temp:
        dump_fields.append("f_Tt[*]")
    if cd.grid_trot and ph.rotate != "no":
        dump_fields.append("f_Tr[*]")
    if cd.grid_tvib and ph.vibrate != "no":
        dump_fields.append("f_Tv[*]")
    if cd.per_species_nrho:
        dump_fields.append("f_nrho_sp[*]")

    geom = "id xlo ylo xhi yhi " if cd.dump_geometry else "id "
    L("# --- Dumps ---")
    L(f"dump           1 grid all ${{window}} {cd.grid_dump_file} "
      f"{geom}{' '.join(dump_fields)}")
    L()


# ══════════════════════════════════════════════════════════════════════════════
#  Numbered computes (surface-mesh / legacy mode)
# ══════════════════════════════════════════════════════════════════════════════

_GRID_FIELDS = [
    ("grid_n", "n"), ("grid_nrho", "nrho"),
    ("grid_u", "u"), ("grid_v", "v"), ("grid_w", "w"),
    ("grid_temp", "temp"),
    ("grid_trot", "trot"), ("grid_erot", "erot"),
    ("grid_tvib", "tvib"), ("grid_evib", "evib"),
    ("grid_press", "press"), ("grid_ke", "ke"),
]
_ROT_KWS = {"trot", "erot"}
_VIB_KWS = {"tvib", "evib"}


def _col_refs(cid: str, ncols: int, prefix: str = "c") -> str:
    return " ".join(f"{prefix}_{cid}[{i+1}]" for i in range(ncols))


def _grid_compute_groups(case):
    cd, ph = case.compute_dump, case.physics
    all_kws = [kw for attr, kw in _GRID_FIELDS if getattr(cd, attr, False)]
    base = [k for k in all_kws if k not in _ROT_KWS | _VIB_KWS]
    rot  = [k for k in all_kws if k in _ROT_KWS] if ph.rotate != "no" else []
    vib  = [k for k in all_kws if k in _VIB_KWS] if ph.vibrate != "no" else []
    groups = []
    if base:
        groups.append(base)
    if rot:
        groups.append(rot)
    if vib:
        groups.append(vib)
    return groups


def _emit_numbered_computes(L, case, has_surf, nevery, nrepeat, nfreq):
    cd = case.compute_dump
    L("# --- Computes ---")
    groups = _grid_compute_groups(case)
    grid_ids, grid_ncols = [], []
    idx = 1
    for kws in groups:
        L(f"compute        {idx} grid all all {' '.join(kws)}")
        grid_ids.append(str(idx)); grid_ncols.append(len(kws)); idx += 1

    surf_id, surf_ncols = "", 0
    if has_surf:
        _SURF = [("surf_n", "n"), ("surf_press", "press"), ("surf_ke", "ke"),
                 ("surf_erot", "erot"), ("surf_evib", "evib"), ("surf_etot", "etot")]
        surf_kws = [kw for attr, kw in _SURF if getattr(cd, attr, False)]
        if surf_kws:
            L(f"compute        {idx} surf all all {' '.join(surf_kws)}")
            surf_id, surf_ncols = str(idx), len(surf_kws); idx += 1
    L()

    L("# --- Time-averaging fixes ---")
    fidx = 1
    for cid, ncols in zip(grid_ids, grid_ncols):
        L(f"fix            {fidx} ave/grid all {nevery} {nrepeat} {nfreq} {_col_refs(cid, ncols)}")
        fidx += 1
    if surf_id:
        L(f"fix            {fidx} ave/surf all {nevery} {nrepeat} {nfreq} {_col_refs(surf_id, surf_ncols)}")
        fidx += 1
    L()

    L("# --- Statistics ---")
    L(f"stats          {cd.stats_nevery}")
    L(f"stats_style    {cd.stats_fields}")
    L()

    L("# --- Dumps ---")
    if grid_ids:
        cols = " ".join(_col_refs(fid, nc, "f") for fid, nc in zip(range(1, len(grid_ids) + 1), grid_ncols))
        geom = "id xlo ylo zlo xhi yhi zhi " if cd.dump_geometry else "id "
        L(f"dump           1 grid all {nfreq} {cd.grid_dump_file} {geom}{cols}")
    L()

    # stash for the run block
    case._numbered_grid_ncols = grid_ncols
    case._numbered_surf_ncols = surf_ncols if surf_id else 0


# ══════════════════════════════════════════════════════════════════════════════
#  Run blocks
# ══════════════════════════════════════════════════════════════════════════════

def _emit_simple_run(L, case, has_surf, warmup, nevery, nrepeat, nfreq):
    """Warmup + reset averages + production, numbered-fix style."""
    sim = case.sim
    grid_ncols = getattr(case, "_numbered_grid_ncols", [])
    surf_ncols = getattr(case, "_numbered_surf_ncols", 0)
    prod_steps = nevery * nrepeat

    L("# --- Run ---")
    L(f"run            {warmup}    # warm-up ({sim.warmup_factor}x flow-through time)")
    L()
    L("# Reset averages before production run")
    fidx = 1
    for _ in grid_ncols:
        L(f"unfix          {fidx}"); fidx += 1
    if surf_ncols:
        L(f"unfix          {fidx}"); fidx += 1
    L()
    fidx = 1
    groups = _grid_compute_groups(case)
    for cid, ncols in zip(range(1, len(groups) + 1), grid_ncols):
        L(f"fix            {fidx} ave/grid all {nevery} {nrepeat} {nfreq} {_col_refs(str(cid), ncols)}")
        fidx += 1
    if surf_ncols:
        surf_cid = len(groups) + 1
        L(f"fix            {fidx} ave/surf all {nevery} {nrepeat} {nfreq} {_col_refs(str(surf_cid), surf_ncols)}")
        fidx += 1
    L()
    if sim.restart_file:
        L(f"write_restart  {sim.restart_file}")
        L()
    L(f"run            {prod_steps}  # production ({nrepeat} samples every {nevery} steps)")
    L()


def _emit_amr_run(L, case, warmup):
    """Warmup + steady-state detection + AMR refinement loop + restart."""
    amr  = case.amr
    sim  = case.sim
    cd   = case.compute_dump
    have_kn = cd.knudsen and cd.per_species_nrho and cd.thermal_temp

    restart = sim.restart_file or "restart/case.restart"
    write_restart = amr.write_restart_on_converge
    nx, ny, nz = amr.cells_split

    L("# ==========================================================================")
    L("# Warm-up run")
    L("# ==========================================================================")
    L()
    L(f"run            {warmup}   # warm-up ({sim.warmup_factor}x flow-through time)")
    L()

    L("# ==========================================================================")
    L("# Steady-state detection + AMR refinement loop")
    L("#")
    L("#   Each iteration advances one averaging window, then compares the")
    L("#   block-averaged particle count (np) to the previous window.  When the")
    L("#   relative change drops below np_threshold the flow is steady: refine the")
    L("#   grid on the per-cell Knudsen number, re-balance, write a restart file,")
    L("#   and keep sampling so the refined grid re-converges.")
    L("#")
    L("#   HOW TO CHECK CONVERGENCE: watch the 'rel_delta' printed each window.")
    L("#   Values below np_threshold mean the particle population is steady.")
    L("# ==========================================================================")
    L()
    L("variable       np_inst      equal np")
    L("fix            npave        ave/time ${freq} ${samples} ${window} v_np_inst ave one")
    L()
    L("variable       np_prev      equal 0.0")
    L(f"variable       np_threshold equal {amr.np_tol}")
    L(f"variable       amr_loops    equal {amr.n_loops}")
    L("variable       amr_done     equal 0")
    L()
    L(f"variable       ss_iter loop {amr.max_iter}")
    L()
    L("label          ss-loop")
    L()
    L("run            ${window}")
    L()
    L("variable       np_curr equal f_npave")
    L()
    L("# First window: no previous value to compare against yet")
    L('if             "${ss_iter} == 1" then                             &')
    L('               "variable np_prev equal ${np_curr}"                &')
    L('               "next ss_iter"                                     &')
    L('               "jump SELF ss-loop"')
    L()
    L("variable       np_delta equal abs(v_np_curr-v_np_prev)/v_np_prev")
    L()
    L('print          "Window ${ss_iter}: np_avg=${np_curr}  rel_delta=${np_delta}  amr_done=${amr_done}"')
    L()

    if have_kn:
        L("# Steady + refinement passes remaining: refine on Kn, balance, restart")
        L('if             "${np_delta} < ${np_threshold} && ${amr_done} < ${amr_loops}" then   &')
        L("               \"print '=== Steady state at window ${ss_iter}: refining grid (pass ${amr_done}) ==='\" &")
        L(f'               "adapt_grid all refine coarsen value f_kn '
          f'{_g(amr.kn_refine_below)} {_g(amr.kn_coarsen_above)} '
          f'thresh less more cells {nx} {ny} {nz}" &')
        L(f'               "balance_grid rcb {case.grid.balance_mode}"                          &')
        L("               \"unfix kn\"                                                          &")
        L("               \"fix kn ave/grid all ${freq} ${samples} ${window} c_kn[2] ave one\"  &")
        if write_restart:
            L(f'               "write_restart {restart}"                                        &')
        L("               \"variable amr_done equal v_amr_done+1\"")
    else:
        L("# (Knudsen field disabled — no AMR refinement performed)")
    L()
    L("variable       np_prev equal ${np_curr}")
    L()
    L("next           ss_iter")
    L("jump           SELF ss-loop")
    L()

    L("# --- Cleanup loop variables ---")
    for v in ("ss_iter", "np_inst", "np_prev", "np_curr", "np_delta",
              "np_threshold", "amr_loops", "amr_done"):
        L(f"variable       {v}  delete")
    L("unfix          npave")
