"""SPARTA .in generator for the CTFL build (relax variable, mgdscollide, etc.).

Picks one of two modes automatically: surface-mesh mode (grid.surface_file, wall
via read_surf + surf_collide) or boundary-wall mode (wall.wall_boundary, the 1D
stagnation-line wall via bound_modify with named computes and an AMR run loop).
"""

from __future__ import annotations

import os
from .engine import DerivedQuantities

_UNIT_SCALES = {"m": 1.0, "mm": 1e-3, "cm": 1e-2, "in": 0.0254}


def _s(v: float, digits: int = 8) -> str:
    return f"{v:.{digits}e}"


def _g(v: float) -> str:
    if v == 0.0:
        return "0"
    if abs(v) >= 1e4 or abs(v) < 1e-3:
        return f"{v:.6e}"
    return f"{v:.8g}"


def _pair(spec: str) -> list[str]:
    """Split a boundary spec into a [lo, hi] pair; a single char applies to both."""
    return [spec[0], spec[1]] if len(spec) > 1 else [spec[0], spec[0]]


def generate(case, derived: DerivedQuantities, dt_override: float = 0.0,
             from_grid: str = "") -> str:
    """Return the SPARTA input script for *case*; dt_override>0 forces the timestep.

    from_grid: if set, read that saved grid instead of create_grid and skip the
    AMR loop (a restart run that samples on the pre-refined grid).
    """
    lines: list[str] = []

    def L(text: str = ""):
        lines.append(text)

    geo  = case.grid
    fs   = case.freestream
    ph   = case.physics
    wall = case.wall
    sim  = case.sim
    cd   = case.compute_dump
    amr  = getattr(case, "amr", None)

    dt = dt_override if dt_override > 0 else derived.dt_recommended
    if dt <= 0:
        dt = 1e-8

    fnum = derived.fnum if derived.fnum > 0 else 1e10
    n_free = derived.n_free if derived.n_free > 0 else 1e20

    # freq=Nevery, samples=Nrepeat, window=Nfreq (coupled: window == freq*samples)
    nevery  = sim.freq
    nrepeat = sim.samples
    nfreq   = sim.window if sim.window > 0 else sim.freq * sim.samples
    warmup  = derived.warmup_steps if derived.warmup_steps > 0 else 10000
    # Round warmup up to a whole window so AMR refinement lands on a fix ave/grid
    # output step (adapt_grid rejects a fix read at an incompatible time).
    if nfreq > 0:
        warmup = -(-warmup // nfreq) * nfreq

    # Zero-fraction inflow species are kept so they're declared in the mixture;
    # fractions normalise over the non-zero entries.
    sp_ids = list(case.species_dict.keys())
    total_frac = sum(f for f in case.species_dict.values() if f > 0)

    # extra_species are reaction products, declared so the species list matches
    # the user's chem file.
    explicit_extra = list(getattr(case, "extra_species", []) or [])
    _extra = [sp for sp in explicit_extra if sp not in sp_ids]
    all_sp_ids = sp_ids + _extra

    has_surf = bool(geo.surface_file)
    # Boundary-wall mode: no surface mesh, wall applied to a box face
    boundary_wall = (not has_surf) and bool(wall.wall_boundary)
    inflow_mix = sim.inflow_mixture if boundary_wall else "all"

    # ── Header ───────────────────────────────────────────────────────────────
    L(f"# SPARTA input script — {case.name}")
    L("# Generated by ctfl-sparta-tools")
    L()
    L("seed           12345")
    L(f"dimension      {geo.dimension}")
    L("units          si")

    pairs = {"x": _pair(geo.boundary_x), "y": _pair(geo.boundary_y), "z": _pair(geo.boundary_z)}
    if geo.symmetry == "axisymmetric" and geo.dimension == 2:
        pairs["y"][0] = "a"   # ylo is the axis of symmetry
        # yhi stays outflow: the decelerated stagnation gas vents radially, as it
        # physically does spreading off the stagnation point. This is the
        # standard stagnation-line closure and is what lets np reach steady state
        # (the radial extent must be a real fraction of the nose radius).
    if boundary_wall:
        # bound_modify requires the wall face be a 's' (surface) boundary
        axis, side = wall.wall_boundary[0], wall.wall_boundary[1:]
        pairs[axis][0 if side == "lo" else 1] = "s"
    L(f"boundary       {''.join(pairs['x'])} {''.join(pairs['y'])} {''.join(pairs['z'])}")
    L()

    # ── Box ──────────────────────────────────────────────────────────────────
    L("# --- Simulation box ---")
    L(f"create_box     {_g(geo.xlo)} {_g(geo.xhi)} {_g(geo.ylo)} {_g(geo.yhi)} {_g(geo.zlo)} {_g(geo.zhi)}")
    # gridcut caps ghost-cell communication so memory stays bounded (2x the
    # freestream MFP). It must precede create_grid/balance_grid: those build the
    # ghost halo, and a later gridcut wipes it, breaking the run.
    if derived.mfp_free > 0:
        L(f"global         gridcut {_s(2.0 * derived.mfp_free)}")
    if from_grid:
        L(f"read_grid      {from_grid}")     # pre-refined grid; no AMR needed
    else:
        L(f"create_grid    {geo.n_cells_x} {geo.n_cells_y} {geo.n_cells_z}")
    L(f"balance_grid   rcb {geo.balance_mode}")
    # Radius weighting equalizes particles/cell across radial rows so near-axis
    # cells (tiny volume) are not starved to 1-2 particles. fnum is sized for
    # this weighting; it holds on any x-refinement (see engine.compute).
    if geo.symmetry == "axisymmetric" and geo.dimension == 2:
        L("global         weight cell radius")
    L()

    # ── Global ────────────────────────────────────────────────────────────────
    L("# --- Global parameters ---")
    L(f"global         nrho {_s(n_free)} fnum {_s(fnum)}")
    L(f"global         vstream {_g(fs.velocity)} 0 0 temp {_g(fs.temperature)}")
    L()

    # ── Timestep ──────────────────────────────────────────────────────────────
    L("# --- Timestep ---")
    L(f"timestep       {_s(dt)}")
    L()

    # ── Species & mixture ─────────────────────────────────────────────────────
    L("# --- Species and mixture ---")
    if all_sp_ids:
        L(f"species        species.list {' '.join(all_sp_ids)}")
        L()
        if boundary_wall:
            # 1D stagnation-line convention: a single 'air' mixture with an
            # explicit emit/face inflow, then per-species fractions.
            L(f"mixture        {inflow_mix} {' '.join(sp_ids)} "
              f"nrho {_s(n_free)} vstream {_g(fs.velocity)} 0 0 temp {_g(fs.temperature)}")
            L()
            if sim.inflow_enabled:
                L(f"fix in1 emit/face {inflow_mix} {sim.inflow_face}")
                L(f"create_particles {inflow_mix} n 0")
                L()
            # Explicit fractions for every species (products get 0)
            for sp in all_sp_ids:
                frac = case.species_dict.get(sp, 0.0) / total_frac if total_frac > 0 else 0.0
                L(f"mixture        {inflow_mix} {sp} frac {_g(frac)}")
        else:
            L(f"mixture        all {' '.join(all_sp_ids)}")
            L(f"mixture        all nrho {_s(n_free)} vstream {_g(fs.velocity)} 0 0 temp {_g(fs.temperature)}")
            L()
            for sp in all_sp_ids:
                frac = case.species_dict.get(sp, 0.0) / total_frac if total_frac > 0 else 0.0
                L(f"mixture        all {sp} frac {_g(frac)}")
    L()

    # ── Surface mesh (only in surface-mesh mode) ──────────────────────────────
    if has_surf:
        surf_base = os.path.basename(geo.surface_file)
        unit_scale = _UNIT_SCALES.get(geo.surface_units, 1.0) * geo.surface_scale
        L("# --- Surface ---")
        if abs(unit_scale - 1.0) > 1e-10:
            L(f"read_surf      {surf_base} scale {_g(unit_scale)} {_g(unit_scale)} {_g(unit_scale)}")
        else:
            L(f"read_surf      {surf_base}")
        L(f"surf_collide   1 diffuse {_g(wall.temperature)} {_g(wall.accommodation)}")
        L("surf_modify    all collide 1")
        L()

    # ── Collision model ───────────────────────────────────────────────────────
    # CTFL: vibration model rides on the collide line via `relax variable vibmodel`.
    if ph.collision_model != "none" and sp_ids:
        L("# --- Collision model ---")
        collide_parts = ["collide vss all collision.list"]
        if ph.rot_relax_model == "parker" or ph.vib_relax_model:
            collide_parts.append("relax variable")
            if ph.vib_relax_model:
                collide_parts.append(f"vibmodel {ph.vib_relax_model}")
        if ph.use_cell_temperature:
            collide_parts.append("usecelltemperature yes")
        if ph.parker_off:
            collide_parts.append("parkeroff yes")
        L(" ".join(collide_parts))

        # collide_modify: rotate/vibrate smoothing + CTFL exchange/MGDS options
        cm_parts = ["collide_modify"]
        cm_parts.append(f"rotate {ph.rotate}")
        cm_parts.append(f"vibrate {ph.vibrate}")
        if ph.exchange_style:
            cm_parts.append(f"exchangestyle {ph.exchange_style}")
        cm_parts.append(f"mgdscollide {'yes' if ph.mgds_collide else 'no'}")
        L(" ".join(cm_parts))
        L()

    # ── Vibrational init (discrete only) ──────────────────────────────────────
    if ph.vibrate == "discrete" and sp_ids:
        t_vib_init = fs.t_vib if fs.t_vib > 0 else fs.temperature
        L("# --- Discrete vibrational energy ---")
        for sp in sp_ids:
            L(f"mixture        {inflow_mix} {sp} tvib {_g(t_vib_init)}")
        L()

    # ── Gas-phase chemistry ───────────────────────────────────────────────────
    if ph.react_enabled:
        react_file = os.path.basename(ph.react_file) if ph.react_file else "air12_sp_complete.chem"
        L("# --- Chemistry ---")
        L(f"react         {ph.react_style} {react_file}")
        if ph.react_modify_partial_energy is not None:
            pe = "yes" if ph.react_modify_partial_energy else "no"
            L(f"react_modify  partial_energy {pe}")
        L()

    # ── Wall boundary conditions ──────────────────────────────────────────────
    if boundary_wall:
        L("# --- Wall boundary conditions ---")
        if wall.surf_react_enabled and wall.surf_react_file:
            L(f"surf_react     {wall.surf_react_id} {wall.surf_react_style} "
              f"{os.path.basename(wall.surf_react_file)}")
        L(f"surf_collide   {wall.surf_collide_id} diffuse "
          f"{_g(wall.temperature)} {_g(wall.accommodation)}")
        L(f"bound_modify   {wall.wall_boundary} collide {wall.surf_collide_id}")
        if wall.surf_react_enabled and wall.surf_react_file:
            L(f"bound_modify   {wall.wall_boundary} react {wall.surf_react_id}")
        L()

    # ── Computes / fixes / stats / dump ───────────────────────────────────────
    if boundary_wall and cd.named_ids:
        _emit_named_computes(L, case, nevery, nrepeat, nfreq, n_species=len(all_sp_ids))
    else:
        _emit_numbered_computes(L, case, has_surf, nevery, nrepeat, nfreq)

    # ── Run ───────────────────────────────────────────────────────────────────
    if from_grid:
        _emit_sampling_run(L, case, warmup)          # pre-refined grid, no AMR
    elif boundary_wall and amr is not None and amr.enabled:
        _emit_amr_run(L, case, warmup)
    else:
        _emit_simple_run(L, case, has_surf, warmup, nevery, nrepeat, nfreq)

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
#  Named computes (boundary-wall / stagnation-line mode)
# ══════════════════════════════════════════════════════════════════════════════

def _dump_ref(fix_id: str, ncols: int) -> str:
    """Dump reference for a fix ave/grid output.

    SPARTA stores a single averaged value as a per-grid vector (f_ID) and
    multiple values as an array (f_ID[*]); mismatching the two is an error.
    """
    return f"f_{fix_id}[*]" if ncols > 1 else f"f_{fix_id}"


def _emit_named_computes(L, case, nevery, nrepeat, nfreq, n_species):
    cd = case.compute_dump
    ph = case.physics

    # Active grid quantities: (id, compute definition, column count).
    grids = [("gridprops", "grid all all n nrho u v", 4)]
    if cd.thermal_temp:
        grids.append(("Tt", "thermal/grid all all temp", 1))
    if cd.grid_trot and ph.rotate != "no":
        grids.append(("Tr", "grid all all trot", 1))
    if cd.grid_tvib and ph.vibrate != "no":
        grids.append(("Tv", "grid all all tvib", 1))
    if cd.per_species_nrho:
        grids.append(("nrho_sp", "grid all species nrho", n_species))
    have_kn = cd.knudsen and cd.per_species_nrho and cd.thermal_temp

    L("# --- Averaging window variables ---")
    L(f"variable       window  equal {nfreq}")
    L(f"variable       samples equal {nrepeat}")
    L(f"variable       freq    equal {nevery}")
    L()

    L("# --- Computes ---")
    for cid, defn, _ in grids:
        L(f"compute        {cid:<9s} {defn}")
    if have_kn:
        L("compute        kn        lambda/grid c_nrho_sp[*] c_Tt[1] lambda knall")
    L()

    # compute grid/thermal/grid always produce an array, so the fix input is
    # always indexed (c_ID[*]); only the fix *output* collapses to a vector.
    L("# --- Time-averaging fixes ---")
    for cid, _, _ in grids:
        L(f"fix            {cid:<9s} ave/grid all ${{freq}} ${{samples}} ${{window}} c_{cid}[*] ave one")
    if have_kn:
        L("fix            kn        ave/grid all ${freq} ${samples} ${window} c_kn[2] ave one")
    L()

    L("# --- Statistics ---")
    L(f"stats          {max(cd.stats_nevery, 1)}")
    L(f"stats_style    {cd.stats_fields}")
    L()

    geom = "id xlo ylo xhi yhi " if cd.dump_geometry else "id "
    dump_fields = " ".join(_dump_ref(cid, ncols) for cid, _, ncols in grids)
    L("# --- Dumps ---")
    L(f"dump           1 grid all ${{window}} {cd.grid_dump_file} {geom}{dump_fields}")
    L()


# ══════════════════════════════════════════════════════════════════════════════
#  Numbered computes (surface-mesh / legacy mode)
# ══════════════════════════════════════════════════════════════════════════════

_GRID_FIELDS = [
    ("grid_n", "n"), ("grid_nrho", "nrho"),
    ("grid_u", "u"), ("grid_v", "v"), ("grid_w", "w"),
    ("grid_temp", "temp"),
    ("grid_trot", "trot"), ("grid_erot", "erot"),
    ("grid_tvib", "tvib"), ("grid_evib", "evib"),
    ("grid_press", "press"), ("grid_ke", "ke"),
]
_ROT_KWS = {"trot", "erot"}
_VIB_KWS = {"tvib", "evib"}


def _col_refs(cid: str, ncols: int, prefix: str = "c") -> str:
    return " ".join(f"{prefix}_{cid}[{i+1}]" for i in range(ncols))


def _grid_compute_groups(case):
    cd, ph = case.compute_dump, case.physics
    all_kws = [kw for attr, kw in _GRID_FIELDS if getattr(cd, attr, False)]
    base = [k for k in all_kws if k not in _ROT_KWS | _VIB_KWS]
    rot  = [k for k in all_kws if k in _ROT_KWS] if ph.rotate != "no" else []
    vib  = [k for k in all_kws if k in _VIB_KWS] if ph.vibrate != "no" else []
    groups = []
    if base:
        groups.append(base)
    if rot:
        groups.append(rot)
    if vib:
        groups.append(vib)
    return groups


def _emit_numbered_computes(L, case, has_surf, nevery, nrepeat, nfreq):
    cd = case.compute_dump
    L("# --- Computes ---")
    groups = _grid_compute_groups(case)
    grid_ids, grid_ncols = [], []
    idx = 1
    for kws in groups:
        L(f"compute        {idx} grid all all {' '.join(kws)}")
        grid_ids.append(str(idx)); grid_ncols.append(len(kws)); idx += 1

    surf_id, surf_ncols = "", 0
    if has_surf:
        _SURF = [("surf_n", "n"), ("surf_press", "press"), ("surf_ke", "ke"),
                 ("surf_erot", "erot"), ("surf_evib", "evib"), ("surf_etot", "etot")]
        surf_kws = [kw for attr, kw in _SURF if getattr(cd, attr, False)]
        if surf_kws:
            L(f"compute        {idx} surf all all {' '.join(surf_kws)}")
            surf_id, surf_ncols = str(idx), len(surf_kws); idx += 1
    L()

    L("# --- Time-averaging fixes ---")
    fidx = 1
    for cid, ncols in zip(grid_ids, grid_ncols):
        L(f"fix            {fidx} ave/grid all {nevery} {nrepeat} {nfreq} {_col_refs(cid, ncols)}")
        fidx += 1
    if surf_id:
        L(f"fix            {fidx} ave/surf all {nevery} {nrepeat} {nfreq} {_col_refs(surf_id, surf_ncols)}")
        fidx += 1
    L()

    L("# --- Statistics ---")
    L(f"stats          {cd.stats_nevery}")
    L(f"stats_style    {cd.stats_fields}")
    L()

    L("# --- Dumps ---")
    if grid_ids:
        cols = " ".join(_dump_ref(str(fid), nc)
                        for fid, nc in zip(range(1, len(grid_ids) + 1), grid_ncols))
        geom = "id xlo ylo zlo xhi yhi zhi " if cd.dump_geometry else "id "
        L(f"dump           1 grid all {nfreq} {cd.grid_dump_file} {geom}{cols}")
    L()

    # stash for the run block
    case._numbered_grid_ncols = grid_ncols
    case._numbered_surf_ncols = surf_ncols if surf_id else 0


# ══════════════════════════════════════════════════════════════════════════════
#  Run blocks
# ══════════════════════════════════════════════════════════════════════════════

def _emit_simple_run(L, case, has_surf, warmup, nevery, nrepeat, nfreq):
    """Warmup + reset averages + production, numbered-fix style."""
    sim = case.sim
    grid_ncols = getattr(case, "_numbered_grid_ncols", [])
    surf_ncols = getattr(case, "_numbered_surf_ncols", 0)
    prod_steps = nevery * nrepeat

    L("# --- Run ---")
    L(f"run            {warmup}    # warm-up ({sim.warmup_factor}x flow-through time)")
    L()
    L("# Reset averages before production run")
    fidx = 1
    for _ in grid_ncols:
        L(f"unfix          {fidx}"); fidx += 1
    if surf_ncols:
        L(f"unfix          {fidx}"); fidx += 1
    L()
    fidx = 1
    groups = _grid_compute_groups(case)
    for cid, ncols in zip(range(1, len(groups) + 1), grid_ncols):
        L(f"fix            {fidx} ave/grid all {nevery} {nrepeat} {nfreq} {_col_refs(str(cid), ncols)}")
        fidx += 1
    if surf_ncols:
        surf_cid = len(groups) + 1
        L(f"fix            {fidx} ave/surf all {nevery} {nrepeat} {nfreq} {_col_refs(str(surf_cid), surf_ncols)}")
        fidx += 1
    L()
    if sim.restart_file:
        L(f"write_restart  {sim.restart_file}")
        L()
    L(f"run            {prod_steps}  # production ({nrepeat} samples every {nevery} steps)")
    L()


def _emit_sampling_run(L, case, warmup):
    """Warmup + sampling on a pre-refined grid (read_grid), no AMR.

    Same wall heat-flux monitor as the AMR run so convergence is judged the same
    way, but the grid is fixed so each window just gathers more statistics.
    """
    wall = case.wall
    wall_row = {"xlo": 1, "xhi": 2, "ylo": 3, "yhi": 4}.get(wall.wall_boundary, 2)

    L("# ==========================================================================")
    L("# Warm-up on the pre-refined grid")
    L("# ==========================================================================")
    L()
    L(f"run            {warmup}   # warm-up ({case.sim.warmup_factor}x flow-through time)")
    L()
    L("# --- Wall heat-flux monitor (watch rel_dq level off) ---")
    L("compute        qwall boundary all etot")
    L(f"variable       qwall_inst equal c_qwall[{wall_row}][1]")
    L("fix            qave ave/time ${freq} ${samples} ${window} v_qwall_inst ave one")
    L()
    L("variable       q_prev  equal 0.0")
    L(f"variable       ss_iter loop {case.amr.max_iter}")
    L("label          sample-loop")
    L("run            ${window}")
    L("variable       q_now  equal f_qave")
    L('variable       q_now  equal ${q_now}')
    L('if             "${q_prev} == 0" then "variable q_prev equal ${q_now}" "next ss_iter" "jump SELF sample-loop"')
    L("variable       q_delta equal abs(${q_now}-${q_prev})/abs(${q_prev})")
    L('print          "Window ${ss_iter}: q_wall=${q_now}  rel_dq=${q_delta}"')
    L("variable       q_prev delete")
    L("variable       q_prev equal ${q_now}")
    L("next           ss_iter")
    L("jump           SELF sample-loop")
    L()
    for v in ("ss_iter", "q_prev", "q_now", "q_delta", "qwall_inst"):
        L(f"variable       {v}  delete")
    L("unfix          qave")


def _emit_amr_run(L, case, warmup):
    """Warmup + steady-state detection + AMR refinement loop + restart."""
    amr  = case.amr
    sim  = case.sim
    cd   = case.compute_dump
    wall = case.wall
    have_kn = cd.knudsen and cd.per_species_nrho and cd.thermal_temp

    grid_file = "grid.adapted"
    # The stagnation-line shock is a purely streamwise feature, so refine x only.
    # Splitting the radial/out-of-plane directions adds no resolution where it
    # matters and quadruples the particle count for the same ppc.
    geo = case.grid
    nx, ny, nz = amr.cells_split[0], 1, 1

    L("# ==========================================================================")
    L("# Warm-up run")
    L("# ==========================================================================")
    L()
    L(f"run            {warmup}   # warm-up ({sim.warmup_factor}x flow-through time)")
    L()

    L("# ==========================================================================")
    L("# Steady-state detection + AMR refinement loop")
    L("#")
    L("#   Convergence is judged on WALL HEAT FLUX, not particle count: the total")
    L("#   energy flux into the wall face is the physical quantity of interest")
    L("#   (stagnation-point heating) and is far more sensitive to a still-")
    L("#   settling shock layer than np is. Each window advances one averaging")
    L("#   window; when the relative change in wall q drops below q_threshold the")
    L("#   flow is steady: refine on Kn, re-balance, restart, keep sampling.")
    L("#")
    L("#   HOW TO CHECK CONVERGENCE: watch 'rel_dq' printed each window; below")
    L("#   q_threshold means the wall heat flux has stopped changing.")
    L("# ==========================================================================")
    L()
    # compute boundary is a per-face array (rows XLO,XHI,YLO,YHI); the wall is
    # xhi = row 2. etot is already normalized to an energy flux (per area/time).
    # fix ave/time can't index a global array element directly, so route it
    # through an equal-style variable first.
    wall_row = {"xlo": 1, "xhi": 2, "ylo": 3, "yhi": 4}.get(wall.wall_boundary, 2)
    L("compute        qwall boundary all etot")
    L(f"variable       qwall_inst equal c_qwall[{wall_row}][1]")
    L("fix            qave ave/time ${freq} ${samples} ${window} v_qwall_inst ave one")
    L()
    L("variable       q_prev      equal 0.0")
    L(f"variable       q_threshold equal {amr.np_tol}")
    L(f"variable       amr_loops    equal {amr.n_loops}")
    L("variable       amr_done     equal 0")
    L()
    L(f"variable       ss_iter loop {amr.max_iter}")
    L()
    L("label          ss-loop")
    L()
    L("run            ${window}")
    L()
    # Snapshot the averaged flux to a plain number so the delta divides by a
    # fixed value, never the still-zero q_prev on the first window.
    L("variable       q_now  equal f_qave")
    L('variable       q_now  equal ${q_now}')
    L()
    L("# First window: seed q_prev and skip the comparison (nothing to compare).")
    L('if             "${q_prev} == 0" then                              &')
    L('               "variable q_prev equal ${q_now}"                   &')
    L('               "next ss_iter"                                     &')
    L('               "jump SELF ss-loop"')
    L()
    L("variable       q_delta equal abs(${q_now}-${q_prev})/abs(${q_prev})")
    L()
    L('print          "Window ${ss_iter}: q_wall=${q_now}  rel_dq=${q_delta}  amr_done=${amr_done}"')
    L()

    if have_kn:
        L("# Steady + refinement passes remaining: refine on Kn, balance, keep sampling")
        L('if             "${q_delta} < ${q_threshold} && ${amr_done} < ${amr_loops}" then    &')
        L("               \"print '=== Steady state at window ${ss_iter}: refining grid (pass ${amr_done}) ==='\" &")
        L(f'               "adapt_grid all refine coarsen value f_kn '
          f'{_g(amr.kn_refine_below)} {_g(amr.kn_coarsen_above)} '
          f'thresh less more cells {nx} {ny} {nz}" &')
        L(f'               "balance_grid rcb {case.grid.balance_mode}"                          &')
        L("               \"unfix kn\"                                                          &")
        L("               \"fix kn ave/grid all ${freq} ${samples} ${window} c_kn[2] ave one\"  &")
        # Increment by expanding the current value; `v_amr_done+1` would be a
        # self-referential formula and recurse until the stack overflows.
        L('               "variable amr_done equal ${amr_done}+1"')
    else:
        L("# (Knudsen field disabled — no AMR refinement performed)")
    L()
    L("variable       q_prev delete")
    L("variable       q_prev equal ${q_now}")
    L()
    L("next           ss_iter")
    L("jump           SELF ss-loop")
    L()

    # Save the refined grid (portable text) so a follow-up run can read_grid it
    # and skip AMR. Not a restart binary — those are machine-specific.
    L("# --- Save the converged, refined grid ---")
    L(f"write_grid      {grid_file}")
    L()

    L("# --- Cleanup loop variables ---")
    for v in ("ss_iter", "q_prev", "q_now", "q_delta", "q_threshold",
              "amr_loops", "amr_done", "qwall_inst"):
        L(f"variable       {v}  delete")
    L("unfix          qave")
