"""SPARTA .in file generator — works with SPARTACase, no Qt dependency."""

from __future__ import annotations

import os
from .engine import DerivedQuantities

_UNIT_SCALES = {"m": 1.0, "mm": 1e-3, "cm": 1e-2, "in": 0.0254}


def _s(v: float, digits: int = 8) -> str:
    return f"{v:.{digits}e}"


def _g(v: float) -> str:
    if v == 0.0:
        return "0"
    if abs(v) >= 1e4 or abs(v) < 1e-3:
        return f"{v:.6e}"
    return f"{v:.8g}"


def generate(case, derived: DerivedQuantities, dt_override: float = 0.0) -> str:
    """Return a complete SPARTA input script string for *case*.

    Parameters
    ----------
    case : SPARTACase
        The fully-specified case object.
    derived : DerivedQuantities
        Pre-computed quantities (from case.derived or engine.compute()).
    dt_override : float
        If > 0, use this timestep instead of the auto-recommended value.
    """
    lines: list[str] = []

    def L(text: str = ""):
        lines.append(text)

    geo = case.grid
    fs  = case.freestream
    ph  = case.physics
    wall = case.wall
    sim = case.sim
    cd  = case.compute_dump

    dt = dt_override if dt_override > 0 else derived.dt_recommended
    if dt <= 0:
        dt = 1e-8

    fnum = derived.fnum if derived.fnum > 0 else 1e10
    n_free = derived.n_free if derived.n_free > 0 else 1e20

    nevery  = sim.ave_nevery
    nrepeat = sim.ave_nrepeat
    nfreq   = sim.ave_nfreq
    prod_steps = nevery * nrepeat
    warmup = derived.warmup_steps if derived.warmup_steps > 0 else 10000

    # Inflow species (non-zero mole fraction) — used for mixture fractions
    sp_ids = [sp for sp, frac in case.species_dict.items() if frac > 0]
    total_frac = sum(case.species_dict.get(sp, 0) for sp in sp_ids)

    # Full species set = inflow + all species that appear in enabled reactions
    # SPARTA only activates reactions whose reactants/products are all declared,
    # but the species command must list every species that can exist in the sim.
    _all_sp_set = set(sp_ids)
    if ph.react_enabled:
        try:
            from .chem_writer import default_gas_reactions, species_in_reactions
            rxn_sp = species_in_reactions(default_gas_reactions())
            _all_sp_set |= rxn_sp
        except Exception:
            pass
    # Preserve inflow order first, then append product-only species alphabetically
    _extra = sorted(_all_sp_set - set(sp_ids))
    all_sp_ids = sp_ids + _extra

    has_surf = bool(geo.surface_file)

    # ── Header ───────────────────────────────────────────────────────────────
    L(f"# SPARTA input script — {case.name}")
    L(f"# Generated by ctfl-sparta-tools")
    L()
    L("seed           12345")
    L(f"dimension      {geo.dimension}")
    L("units          si")

    bx = geo.boundary_x
    by = geo.boundary_y
    bz = geo.boundary_z
    if geo.symmetry == "axisymmetric" and geo.dimension == 2:
        by = "a" + (by[1] if len(by) > 1 else "o")
    L(f"boundary       {bx} {by} {bz}")
    L()

    # ── Box ──────────────────────────────────────────────────────────────────
    L("# --- Simulation box ---")
    L(f"create_box     {_g(geo.xlo)} {_g(geo.xhi)} {_g(geo.ylo)} {_g(geo.yhi)} {_g(geo.zlo)} {_g(geo.zhi)}")
    L(f"create_grid    {geo.n_cells_x} {geo.n_cells_y} {geo.n_cells_z}")
    L("balance_grid   rcb part")
    L()

    # ── Global ────────────────────────────────────────────────────────────────
    L("# --- Global parameters ---")
    L(f"global         nrho {_s(n_free)} fnum {_s(fnum)} gridcut 0.0")
    L(f"global         vstream {_g(fs.velocity)} 0 0 temp {_g(fs.temperature)}")
    L()

    # ── Timestep ──────────────────────────────────────────────────────────────
    L("# --- Timestep ---")
    L(f"timestep       {_s(dt)}")
    L()

    # ── Species & mixture ─────────────────────────────────────────────────────
    L("# --- Species and mixture ---")
    sp_file_base = "species.list"
    if all_sp_ids:
        # Declare ALL possible species (inflow + reaction products)
        L(f"species        {sp_file_base} {' '.join(all_sp_ids)}")
        L()
        # mixture global: set bulk properties using inflow species only
        mix_parts = [f"mixture        all {' '.join(all_sp_ids)}",
                     f"nrho {_s(n_free)}",
                     f"vstream {_g(fs.velocity)} 0 0",
                     f"temp {_g(fs.temperature)}"]
        if ph.vibrate == "discrete" and fs.t_vib > 0:
            mix_parts.append(f"tvib {_g(fs.t_vib)}")
        L(" ".join(mix_parts))
        L()
        # Set mole fractions — inflow species get their fractions, products get 0
        for sp in all_sp_ids:
            frac = case.species_dict.get(sp, 0.0) / total_frac if total_frac > 0 else 0.0
            L(f"mixture        all {sp} frac {_g(frac)}")
    L()

    # ── Surface ───────────────────────────────────────────────────────────────
    if has_surf:
        surf_base = os.path.basename(geo.surface_file)
        unit_scale = _UNIT_SCALES.get(geo.surface_units, 1.0) * geo.surface_scale
        L("# --- Surface ---")
        if abs(unit_scale - 1.0) > 1e-10:
            L(f"read_surf      {surf_base} scale {_g(unit_scale)} {_g(unit_scale)} {_g(unit_scale)}")
        else:
            L(f"read_surf      {surf_base}")
        L(f"surf_collide   1 diffuse {_g(wall.temperature)} {_g(wall.accommodation)}")
        L("surf_modify    all collide 1")
        L()

    # ── Collision model ───────────────────────────────────────────────────────
    if ph.collision_model != "none" and sp_ids:
        coll_base = "collision.vss"
        relax_kw = "variable" if ph.rot_relax_model == "parker" else "constant"
        L("# --- Collision model ---")
        L(f"collide        vss all {coll_base} relax {relax_kw} vibmodel {ph.vib_relax_model}")
        L()
        cm_parts = ["collide_modify",
                    f"rotate {'no' if ph.rotate == 'no' else ph.rotate}",
                    f"vibrate {'no' if ph.vibrate == 'no' else ph.vibrate}"]
        if ph.use_cell_temperature:
            cm_parts.append("usecelltemperature yes")
        L(" ".join(cm_parts))
        L()

    # ── Vibrational init ──────────────────────────────────────────────────────
    if ph.vibrate == "discrete" and all_sp_ids:
        t_vib_init = fs.t_vib if fs.t_vib > 0 else fs.temperature
        L("# --- Discrete vibrational energy ---")
        for sp in all_sp_ids:
            L(f"mixture        all {sp} tvib {_g(t_vib_init)}")
        L()

    # ── Chemistry ─────────────────────────────────────────────────────────────
    if ph.react_enabled and ph.react_file:
        L("# --- Chemistry ---")
        L(f"react          {ph.react_style} {os.path.basename(ph.react_file)}")
        L()
    elif ph.react_enabled:
        # react enabled but no file path supplied — use auto-generated file
        L("# --- Chemistry ---")
        L(f"react          {ph.react_style} air.chem")
        L()

    # Surface chemistry (surf_react prob style)
    surf_react_file = getattr(case, "_surf_react_file", "")
    if surf_react_file:
        L("# --- Surface chemistry ---")
        L(f"surf_react     1 prob {os.path.basename(surf_react_file)}")
        L("surf_modify    all react 1")
        L()

    # ── Computes ──────────────────────────────────────────────────────────────
    L("# --- Computes ---")

    _GRID_FIELDS = [
        ("grid_n",     "n"),     ("grid_nrho",  "nrho"),
        ("grid_u",     "u"),     ("grid_v",     "v"),     ("grid_w",    "w"),
        ("grid_temp",  "temp"),
        ("grid_trot",  "trot"),  ("grid_erot",  "erot"),
        ("grid_tvib",  "tvib"),  ("grid_evib",  "evib"),
        ("grid_press", "press"), ("grid_ke",    "ke"),
    ]
    _ROT_KWS = {"trot", "erot"}
    _VIB_KWS = {"tvib", "evib"}

    all_grid_kws = [kw for attr, kw in _GRID_FIELDS if getattr(cd, attr, False)]
    base_kws = [k for k in all_grid_kws if k not in _ROT_KWS | _VIB_KWS]
    rot_kws  = [k for k in all_grid_kws if k in _ROT_KWS]
    vib_kws  = [k for k in all_grid_kws if k in _VIB_KWS]

    compute_idx = 1
    grid_compute_ids: list[str] = []

    if base_kws:
        L(f"compute        {compute_idx} grid all all {' '.join(base_kws)}")
        grid_compute_ids.append(str(compute_idx)); compute_idx += 1
    if rot_kws and ph.rotate != "no":
        L(f"compute        {compute_idx} grid all all {' '.join(rot_kws)}")
        grid_compute_ids.append(str(compute_idx)); compute_idx += 1
    if vib_kws and ph.vibrate != "no":
        L(f"compute        {compute_idx} grid all all {' '.join(vib_kws)}")
        grid_compute_ids.append(str(compute_idx)); compute_idx += 1

    surf_compute_id = ""
    if has_surf:
        _SURF_FIELDS = [
            ("surf_n", "n"), ("surf_press", "press"), ("surf_ke", "ke"),
            ("surf_erot", "erot"), ("surf_evib", "evib"), ("surf_etot", "etot"),
        ]
        surf_kws = [kw for attr, kw in _SURF_FIELDS if getattr(cd, attr, False)]
        if surf_kws:
            L(f"compute        {compute_idx} surf all all {' '.join(surf_kws)}")
            surf_compute_id = str(compute_idx); compute_idx += 1
    L()

    # ── Fixes ─────────────────────────────────────────────────────────────────
    L("# --- Time-averaging fixes ---")
    fix_idx = 1
    grid_fix_ids: list[str] = []
    for cid in grid_compute_ids:
        L(f"fix            {fix_idx} ave/grid all {nevery} {nrepeat} {nfreq} c_{cid}[*]")
        grid_fix_ids.append(str(fix_idx)); fix_idx += 1
    surf_fix_id = ""
    if surf_compute_id:
        L(f"fix            {fix_idx} ave/surf all {nevery} {nrepeat} {nfreq} c_{surf_compute_id}[*]")
        surf_fix_id = str(fix_idx); fix_idx += 1
    L()

    # ── Stats ─────────────────────────────────────────────────────────────────
    L("# --- Statistics ---")
    L(f"stats          {cd.stats_nevery}")
    L(f"stats_style    {cd.stats_fields}")
    L()

    # ── Dumps ─────────────────────────────────────────────────────────────────
    L("# --- Dumps ---")
    dump_idx = 1
    if grid_fix_ids:
        fix_cols = " ".join(f"f_{fid}[*]" for fid in grid_fix_ids)
        L(f"dump           {dump_idx} grid all {nfreq} {cd.grid_dump_file} id xlo ylo zlo xhi yhi zhi {fix_cols}")
        dump_idx += 1
    if surf_fix_id:
        L(f"dump           {dump_idx} surf all {nfreq} {cd.surf_dump_file} id f_{surf_fix_id}[*]")
        dump_idx += 1
    if cd.particle_dump_enabled:
        p_nevery = cd.particle_dump_nevery if cd.particle_dump_nevery > 0 else nfreq
        L(f"dump           {dump_idx} particle all {p_nevery} {cd.particle_dump_file} id x y z vx vy vz")
        dump_idx += 1
    L()

    # ── Run — warmup ──────────────────────────────────────────────────────────
    L("# --- Run ---")
    L(f"run            {warmup}    # warm-up ({sim.warmup_factor}× flow-through time)")
    L()
    L("# Reset averages before production run")
    for fid in grid_fix_ids:
        L(f"unfix          {fid}")
    if surf_fix_id:
        L(f"unfix          {surf_fix_id}")
    L()
    fix_idx = 1
    for cid in grid_compute_ids:
        L(f"fix            {fix_idx} ave/grid all {nevery} {nrepeat} {nfreq} c_{cid}[*]")
        fix_idx += 1
    if surf_compute_id:
        L(f"fix            {fix_idx} ave/surf all {nevery} {nrepeat} {nfreq} c_{surf_compute_id}[*]")
        fix_idx += 1
    L()
    L(f"run            {prod_steps}  # production ({nrepeat} samples every {nevery} steps, output every {nfreq})")
    L()

    return "\n".join(lines)
