"""Plain-language README generator for a SPARTA case package.

Written for users from a continuum / CFD background who are new to DSMC and
SPARTA.  Explains what the case is, how to run it, and — most importantly —
how to tell when the simulation has converged.
"""

from __future__ import annotations


def generate_readme(case, in_name: str, artifacts: dict) -> str:
    d = case.derived
    fs = case.freestream
    geo = case.grid
    sim = case.sim
    amr = getattr(case, "amr", None)
    cd = case.compute_dump

    def line(*parts):
        L.append("".join(str(p) for p in parts))

    L: list[str] = []

    # ── Title ─────────────────────────────────────────────────────────────────
    line(f"# SPARTA DSMC case: `{case.name}`")
    line()
    line("This package was generated by **ctfl-sparta-tools**.  It contains "
         "everything needed to run a 1-D axisymmetric (stagnation-line) DSMC "
         "simulation with SPARTA — just upload the whole folder to your machine "
         "or cluster and run it.")
    line()

    # ── What this simulates ───────────────────────────────────────────────────
    line("## What this case simulates")
    line()
    line("A blunt-body re-entry flow, reduced to the **stagnation streamline**: "
         "freestream gas enters on one side, passes through a bow shock, and "
         "strikes the wall.  The `x`-axis is the stagnation line; `x = "
         f"{_fmt(geo.xhi)}` m is the wall (surface), and `x = {_fmt(geo.xlo)}` m "
         "is the freestream inlet.")
    line()
    line("**Freestream conditions:**")
    line()
    line(f"| Quantity | Value |")
    line(f"|---|---|")
    line(f"| Velocity | {_fmt(fs.velocity)} m/s |")
    line(f"| Temperature | {_fmt(fs.temperature)} K |")
    if fs.pressure:
        line(f"| Pressure | {_fmt(fs.pressure)} Pa |")
    if not d.error:
        line(f"| Mach number | {d.mach:.2f} |")
        line(f"| Number density n∞ | {d.n_free:.3e} m⁻³ |")
        line(f"| Mean free path λ∞ | {d.mfp_free:.3e} m |")
        line(f"| Knudsen number Kn∞ | {d.kn_free:.3e} |")
        if d.T_shock:
            line(f"| Post-shock temperature | {d.T_shock:.0f} K |")
    line(f"| Wall temperature | {_fmt(case.wall.temperature)} K |")
    line()
    line("**Species:** " + ", ".join(case.species_dict.keys()) +
         (" (+ reaction products: " + ", ".join(case.extra_species) + ")"
          if case.extra_species else ""))
    line()

    # ── Files ─────────────────────────────────────────────────────────────────
    line("## Files in this package")
    line()
    line("| File | Purpose |")
    line("|---|---|")
    line(f"| `{in_name}` | The SPARTA input script — run this |")
    if "species" in artifacts:
        line("| `species.list` | Per-species molecular data |")
    if "collision" in artifacts:
        line("| `collision.list` | VSS collision parameters |")
    if "gas_chem" in artifacts:
        line(f"| `{_base(case.physics.react_file)}` | Gas-phase reactions (TCE) |")
    if "wall_chem" in artifacts:
        line(f"| `{_base(case.wall.surf_react_file)}` | Surface (wall) chemistry |")
    if "data_dir" in artifacts:
        line("| `data/` | Grid dump output (written during the run) |")
    if "restart_dir" in artifacts:
        line("| `restart/` | Restart checkpoint (written at steady state) |")
    line()

    # ── How to run ────────────────────────────────────────────────────────────
    line("## How to run")
    line()
    line("SPARTA runs under MPI.  From inside this folder:")
    line()
    line("```bash")
    line(f"# Serial (small / testing):")
    line(f"spa_ < {in_name}")
    line()
    line(f"# Parallel (recommended) — replace 8 with your core count:")
    line(f"mpirun -np 8 spa_ -in {in_name} -log log.{case.name}")
    line("```")
    line()
    line("Replace `spa_` with the name of your SPARTA executable "
         "(often `spa_mpi` or a full path to it).")
    line()
    line("### Example SLURM job script")
    line()
    line("```bash")
    line("#!/bin/bash")
    line(f"#SBATCH --job-name={case.name}")
    line("#SBATCH --nodes=1")
    line("#SBATCH --ntasks=32")
    line("#SBATCH --time=24:00:00")
    line("")
    line("module load sparta      # or your site's module")
    line(f"mpirun spa_mpi -in {in_name} -log log.{case.name}")
    line("```")
    line()

    # ── Convergence — the important part ──────────────────────────────────────
    line("## How to check convergence")
    line()
    line("This is the part that matters for trustworthy results.  The run has "
         "**two phases**:")
    line()
    line(f"1. **Warm-up** ({d.warmup_steps:,} steps): the flow fills the domain "
         "and the shock forms.  Statistics here are meaningless — this just "
         "reaches a physical state.")
    line()
    if amr is not None and amr.enabled:
        line("2. **Steady-state + AMR loop**: the script advances one averaging "
             f"window ({sim.window:,} steps) at a time and prints a line like:")
        line()
        line("   ```")
        line("   Window 3: np_avg=1.75e5  rel_delta=0.043  amr_done=0")
        line("   ```")
        line()
        line("   * **`np_avg`** — average particle count in the domain over that "
             "window.")
        line("   * **`rel_delta`** — relative change in `np_avg` versus the "
             "previous window.  This is your convergence metric.")
        line(f"   * When `rel_delta` drops below **{amr.np_tol}**, the flow is "
             "considered steady.  The grid is then **refined** on the local "
             "Knudsen number (so the shock is well-resolved), re-balanced across "
             "MPI ranks, and a **restart file** is written.")
        line(f"   * The loop repeats up to **{amr.max_iter}** windows to let the "
             "refined grid re-converge.")
        line()
        line("**What good convergence looks like:** `rel_delta` decreases "
             "monotonically toward zero and stays below the threshold across "
             "several consecutive windows *after* the final refinement.  If it "
             "keeps oscillating, increase `samples` (more samples per window) — "
             "but keep `window == freq * samples` (the library enforces this).")
    else:
        line("2. **Production** — averaged grid data is dumped to `data/`.")
    line()
    line("You can also plot the grid dumps in `data/` (e.g. temperature or "
         "velocity along the stagnation line) between windows; when the profiles "
         "stop changing, you are converged.")
    line()

    # ── Restarting ────────────────────────────────────────────────────────────
    restart = sim.restart_file or (
        "restart/case.restart" if (amr is not None and amr.enabled) else "")
    if restart:
        line("## Restarting from steady state")
        line()
        line(f"Once steady state is reached, a restart file is written to "
             f"`{restart}`.  To continue a run (e.g. gather more statistics or "
             "change wall chemistry) without redoing the warm-up, start a new "
             "input script with:")
        line()
        line("```")
        line(f"read_restart   {restart}")
        line("```")
        line()
        line("instead of the `create_box` / `create_grid` / `create_particles` "
             "commands.  All grid, particle, and species state is restored.")
        line()

    # ── Tuning knobs ──────────────────────────────────────────────────────────
    line("## Common things to adjust")
    line()
    line("Open the generator script (Python) or the `.toml` config and change:")
    line()
    line("| To do this | Change |")
    line("|---|---|")
    line("| Different freestream | `velocity`, `temperature`, `pressure` |")
    line("| Different wall temperature | `WallConfig.temperature` |")
    line("| Finer/coarser starting grid | `target_cells` (MFP-checked automatically) |")
    line("| Better statistics | raise `samples` (keep `window = freq * samples`) |")
    if amr is not None:
        line("| Refine shock harder | lower `AMRConfig.kn_refine_below` |")
        line("| Declare steady state sooner | raise `AMRConfig.np_tol` |")
        line("| More refinement passes | raise `AMRConfig.n_loops` |")
    line()
    line("After editing, re-generate the package and re-upload.")
    line()
    line("---")
    line("_Questions: contact the CTFL group (saviopoovathingal@uky.edu)._")
    line()

    return "\n".join(L)


def _fmt(v: float) -> str:
    if v == 0:
        return "0"
    if abs(v) >= 1e4 or abs(v) < 1e-3:
        return f"{v:.4e}"
    return f"{v:g}"


def _base(path: str) -> str:
    import os
    return os.path.basename(path) if path else ""
