"""Generate SPARTA species and VSS collision files from species.json database.

SPARTA species file format (one line per species):
  id molwt rotdof rotrel rottemp vibdof vibrel vibtemp specieswt charge

SPARTA VSS/VHS collision file format (one pair per line):
  sp1 sp2 diam omega tref alpha
where diam = reference diameter, omega = viscosity index, tref = reference temp,
alpha = VSS angular scattering parameter (1.0 = VHS).

The reference diameter is computed from the stored diameter field.
"""

from __future__ import annotations

import json
import math
import os


def _load_db(species_file: str) -> dict:
    if not species_file or not os.path.isfile(species_file):
        return {}
    with open(species_file) as f:
        return json.load(f)


def write_species_file(
    species_ids: list[str],
    species_file: str,
    overrides: dict | None = None,
    *,
    out_path: str = "",
) -> str:
    """Generate a SPARTA species file for the given species list.

    Parameters
    ----------
    species_ids : list[str]
        Species identifiers to include (in order).
    species_file : str
        Path to species.json database.
    overrides : dict, optional
        Mapping of species_id → {field: value} for per-species parameter overrides.
    out_path : str, optional
        If non-empty, write to this path and return the path.
        If empty, return the file content as a string.
    """
    db = _load_db(species_file)
    overrides = overrides or {}

    lines = [
        "# SPARTA species file — generated by ctfl-sparta-tools",
        "# Format: id  molwt  rotdof  rotrel  rottemp  vibdof  vibrel  vibtemp  specieswt  charge",
        "#",
    ]

    for sp in species_ids:
        if sp not in db:
            lines.append(f"# WARNING: '{sp}' not found in species database — skipped")
            continue
        d = dict(db[sp])
        if sp in overrides:
            d.update(overrides[sp])

        lines.append(
            f"{sp:<8s} "
            f"{d['molwt']:<12g} "
            f"{d['rotdof']:<8g} "
            f"{d['rotrel']:<12g} "
            f"{d['rottemp']:<12g} "
            f"{d['vibdof']:<8g} "
            f"{d['vibrel']:<16g} "
            f"{d['vibtemp']:<12g} "
            f"{d['specieswt']:<12g} "
            f"{d['charge']:<g}"
        )

    content = "\n".join(lines) + "\n"

    if out_path:
        with open(out_path, "w") as f:
            f.write(content)
        return out_path
    return content


def write_collision_file(
    species_ids: list[str],
    species_file: str,
    overrides: dict | None = None,
    *,
    out_path: str = "",
    relax_variable: bool = True,
) -> str:
    """Generate a SPARTA VSS collision (parameter) file.

    SPARTA's ``collide vss`` parser has two line formats depending on whether the
    ``relax variable`` keyword is used on the collide command:

    * ``relax variable`` (CTFL default, ``relax_variable=True``): each species
      line needs **11 fields** ::

          id  diam  omega  tref  alpha  rotc1  rotc2  vibc1  vibc2  MW_A  MW_B

      Cross-species pairs are optional — SPARTA averages self-species values for
      any pair not explicitly given — so only self-species lines are emitted.

    * constant relaxation (``relax_variable=False``): each line needs 5 fields
      (``id diam omega tref alpha``); cross-species pairs are averaged too.

    Parameters
    ----------
    species_ids : list[str]
        Species to include (self-species lines are written for each).
    species_file : str
        Path to species.json database.
    overrides : dict, optional
        Mapping of species_id → {field: value} for per-species parameter overrides.
    out_path : str, optional
        Write to file if non-empty; otherwise return as string.
    relax_variable : bool
        Emit the 11-field VARIABLE format (default) or the 5-field constant format.
    """
    db = _load_db(species_file)
    overrides = overrides or {}

    if relax_variable:
        lines = [
            "# SPARTA VSS collision file — generated by ctfl-sparta-tools",
            "# relax variable format (11 fields):",
            "#   id  diam  omega  tref  alpha  rotc1  rotc2  vibc1  vibc2  MW_A  MW_B",
            "#   diam=ref diameter (m), omega=viscosity index, tref=ref temp (K),",
            "#   alpha=VSS scattering, rotc*/vibc*/MW_*=Parker & Millikan-White params",
            "#",
        ]
    else:
        lines = [
            "# SPARTA VSS collision file — generated by ctfl-sparta-tools",
            "# constant relax format (5 fields): id  diam  omega  tref  alpha",
            "#",
        ]

    for sp in species_ids:
        if sp not in db:
            lines.append(f"# WARNING: '{sp}' not found in species database — skipped")
            continue
        e = db[sp]
        p = {
            "diam":  e.get("diameter", 0.0),
            "omega": e.get("omega", 0.75),
            "tref":  e.get("tref", 273.15),
            "alpha": e.get("alpha", 1.0),
            "rotc1": e.get("rotc1", 0.0),
            "rotc2": e.get("rotc2", 0.0),
            "vibc1": e.get("birdc1", 0.0),
            "vibc2": e.get("birdc2", 0.0),
            "MW_A":  e.get("MWA", 0.0),
            "MW_B":  e.get("MWB", 0.0),
        }
        if sp in overrides:
            p.update(overrides[sp])

        if relax_variable:
            lines.append(
                f"{sp:<8s} "
                f"{p['diam']:.6e}  {p['omega']:.6f}  {p['tref']:.4f}  {p['alpha']:.6f}  "
                f"{p['rotc1']:g} {p['rotc2']:g} {p['vibc1']:g} {p['vibc2']:g} "
                f"{p['MW_A']:g} {p['MW_B']:g}"
            )
        else:
            lines.append(
                f"{sp:<8s} "
                f"{p['diam']:.6e}  {p['omega']:.6f}  {p['tref']:.4f}  {p['alpha']:.6f}"
            )

    content = "\n".join(lines) + "\n"

    if out_path:
        with open(out_path, "w") as f:
            f.write(content)
        return out_path
    return content
