"""Generate SPARTA species and VSS collision files from species.json database.

SPARTA species file format (one line per species):
  id molwt rotdof rotrel rottemp vibdof vibrel vibtemp specieswt charge

SPARTA VSS/VHS collision file format (one pair per line):
  sp1 sp2 diam omega tref alpha
where diam = reference diameter, omega = viscosity index, tref = reference temp,
alpha = VSS angular scattering parameter (1.0 = VHS).

The reference diameter is computed from the stored diameter field.
"""

from __future__ import annotations

import json
import math
import os


def _load_db(species_file: str) -> dict:
    if not species_file or not os.path.isfile(species_file):
        return {}
    with open(species_file) as f:
        return json.load(f)


def write_species_file(
    species_ids: list[str],
    species_file: str,
    overrides: dict | None = None,
    *,
    out_path: str = "",
) -> str:
    """Generate a SPARTA species file for the given species list.

    Parameters
    ----------
    species_ids : list[str]
        Species identifiers to include (in order).
    species_file : str
        Path to species.json database.
    overrides : dict, optional
        Mapping of species_id → {field: value} for per-species parameter overrides.
    out_path : str, optional
        If non-empty, write to this path and return the path.
        If empty, return the file content as a string.
    """
    db = _load_db(species_file)
    overrides = overrides or {}

    lines = [
        "# SPARTA species file — generated by ctfl-sparta-tools",
        "# Format: id  molwt  rotdof  rotrel  rottemp  vibdof  vibrel  vibtemp  specieswt  charge",
        "#",
    ]

    for sp in species_ids:
        if sp not in db:
            lines.append(f"# WARNING: '{sp}' not found in species database — skipped")
            continue
        d = dict(db[sp])
        if sp in overrides:
            d.update(overrides[sp])

        lines.append(
            f"{sp:<8s} "
            f"{d['molwt']:<12g} "
            f"{d['rotdof']:<8g} "
            f"{d['rotrel']:<12g} "
            f"{d['rottemp']:<12g} "
            f"{d['vibdof']:<8g} "
            f"{d['vibrel']:<16g} "
            f"{d['vibtemp']:<12g} "
            f"{d['specieswt']:<12g} "
            f"{d['charge']:<g}"
        )

    content = "\n".join(lines) + "\n"

    if out_path:
        with open(out_path, "w") as f:
            f.write(content)
        return out_path
    return content


def write_collision_file(
    species_ids: list[str],
    species_file: str,
    overrides: dict | None = None,
    *,
    out_path: str = "",
) -> str:
    """Generate a SPARTA VSS collision file for all pairs of the given species.

    Parameters
    ----------
    species_ids : list[str]
        Active species (only pairs of these are emitted).
    species_file : str
        Path to species.json database.
    overrides : dict, optional
        Mapping of "sp1-sp2" → {field: value} for per-pair parameter overrides.
        Pair key is sorted alphabetically: "N2-O2" not "O2-N2".
    out_path : str, optional
        Write to file if non-empty; otherwise return as string.
    """
    db = _load_db(species_file)
    overrides = overrides or {}

    lines = [
        "# SPARTA VSS collision file — generated by ctfl-sparta-tools",
        "# Format: sp1  sp2  diam  omega  tref  alpha",
        "# diam = reference diameter (m), omega = viscosity index,",
        "# tref = reference temperature (K), alpha = VSS scattering (1.0 = VHS)",
        "#",
    ]

    def _pair_params(sp1: str, sp2: str) -> dict:
        d1 = db.get(sp1, {})
        d2 = db.get(sp2, {})
        # Mixing rules: arithmetic mean for diameter, geometric mean for omega
        diam  = 0.5 * (d1.get("diameter", 0) + d2.get("diameter", 0))
        omega = 0.5 * (d1.get("omega", 0.75) + d2.get("omega", 0.75))
        tref  = 0.5 * (d1.get("tref", 273.15) + d2.get("tref", 273.15))
        alpha = 0.5 * (d1.get("alpha", 1.0) + d2.get("alpha", 1.0))
        return {"diam": diam, "omega": omega, "tref": tref, "alpha": alpha}

    for i, sp1 in enumerate(species_ids):
        for sp2 in species_ids[i:]:
            if sp1 not in db or sp2 not in db:
                continue
            key = "-".join(sorted([sp1, sp2]))
            p = _pair_params(sp1, sp2)
            if key in overrides:
                p.update(overrides[key])
            lines.append(
                f"{sp1:<8s} {sp2:<8s} "
                f"{p['diam']:.6e}  "
                f"{p['omega']:.6f}  "
                f"{p['tref']:.4f}  "
                f"{p['alpha']:.6f}"
            )

    content = "\n".join(lines) + "\n"

    if out_path:
        with open(out_path, "w") as f:
            f.write(content)
        return out_path
    return content
